### PR TITLE
[RFR] to avoid public access to source code of the automaton

### PR DESCRIPTION
**Pull request by touv**

### CODE REVIEW

**Comment by parmentf** [comment]
Where did you generate such an image?
I'm curious.
I did not found when I searched, for JBJ.

**Comment by parmentf** [comment]
Wouldn't it be more sure, if you used the `-d false` option of `http-server`?

https://github.com/indexzero/http-server#available-options

**Comment by kerphi** [comment]
Missing stuff in the dockerfile and package.json

The public/ folder is not added to the image
And http-server is not pointing on public when starting in package.json ?

**Comment by kerphi** [comment]
up ?

**Comment by touv** [comment]
oups... no config needs 

image

**Pull request merged**
